version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '5433:5432'
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: password
    networks:
      - keycloak-network

  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: '5432'
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_NAME: postgres
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    volumes:
      - ./KeyCloak:/opt/bitnami/Keycloak/data/import
    networks:
      - keycloak-network
    depends_on:
      - postgresql

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
